import {
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

// WHY THIS FILE EXISTS
// An "entity" is a class that describes one database table. TypeORM reads it
// to generate migrations and to load/save rows as objects. This one is the
// `users` table: the account itself (identity only, no game stats).
// Column names in the database are snake_case; in code they are camelCase,
// connected by the `name` option.
@Entity('users')
export class User {
  // uuid generated by the database, not guessable like 1, 2, 3...
  @PrimaryGeneratedColumn('uuid')
  id: string;

  // Login identifier. Unique. The service lowercases it before saving, so
  // "A@x.com" and "a@x.com" cannot be two accounts.
  @Column({ type: 'text', unique: true })
  email: string;

  // Public name shown in matches and on the leaderboard. Unique.
  @Column({ name: 'display_name', type: 'text', unique: true })
  displayName: string;

  // null for accounts that only log in through OAuth (no password set).
  @Column({ name: 'password_hash', type: 'text', nullable: true })
  passwordHash: string | null;

  @Column({ name: 'avatar_url', type: 'text', nullable: true })
  avatarUrl: string | null;

  // Interface language: en, fr or ar (matches the frontend's i18n).
  @Column({ type: 'text', default: 'en' })
  locale: string;

  // Filled by the database when the row is inserted.
  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;

  // Refreshed automatically on every update.
  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt: Date;
}
