import { MigrationInterface, QueryRunner } from "typeorm";

// WHAT THIS FILE IS
// A migration generated by `npm run migration:generate` from
// src/modules/tournaments/entities/tournament-pairing.entity.ts. It adds the
// bracket of a tournament: one row per pairing, identified by (tournament,
// round, position), with its two players, its match and its winner.
//  - a pairing needs two different players, and its winner must be one of them
//    (CHECKs); the players stay empty while the slot waits for earlier winners
//  - deleting a tournament deletes its bracket (CASCADE); deleting a match only
//    empties the slot's match_id (SET NULL); players are RESTRICTed like in
//    the other result tables
//  - match_id is indexed: when a match ends, its pairing is found from there
//
// DO NOT rename this file or class after it has run, and never change its SQL
// afterwards: change the entity and generate a NEW migration instead.
export class CreateTournamentPairings1791584714008 implements MigrationInterface {
    name = 'CreateTournamentPairings1791584714008'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "tournament_pairings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tournament_id" uuid NOT NULL, "round" smallint NOT NULL, "position" smallint NOT NULL, "player1_id" uuid, "player2_id" uuid, "match_id" uuid, "winner_id" uuid, "bye" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_4eb8e70c925a42b8ef1569c404e" UNIQUE ("tournament_id", "round", "position"), CONSTRAINT "CHK_0d7b7d31fcb3f06654ee62ff81" CHECK ("winner_id" IS NULL OR "winner_id" IN ("player1_id", "player2_id")), CONSTRAINT "CHK_fe16985f525693df7047b2308e" CHECK ("player1_id" <> "player2_id"), CONSTRAINT "CHK_dc185800815ab3e2376bedca97" CHECK ("round" >= 0 AND "position" >= 0), CONSTRAINT "PK_115d81a0b40ff548e87aa86d7ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_156afe22bb6ce336df01988d1e" ON "tournament_pairings"  ("match_id") `);
        await queryRunner.query(`ALTER TABLE "tournament_pairings" ADD CONSTRAINT "FK_935d21edc31e8136616958c18a9" FOREIGN KEY ("tournament_id") REFERENCES "tournaments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_pairings" ADD CONSTRAINT "FK_04e2b3dc93651026e3656f9c836" FOREIGN KEY ("player1_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_pairings" ADD CONSTRAINT "FK_4f70c0d8fa9e9ea442fa7a8756e" FOREIGN KEY ("player2_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_pairings" ADD CONSTRAINT "FK_156afe22bb6ce336df01988d1e7" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_pairings" ADD CONSTRAINT "FK_c6724474509294f96654c25f5e0" FOREIGN KEY ("winner_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tournament_pairings" DROP CONSTRAINT "FK_c6724474509294f96654c25f5e0"`);
        await queryRunner.query(`ALTER TABLE "tournament_pairings" DROP CONSTRAINT "FK_156afe22bb6ce336df01988d1e7"`);
        await queryRunner.query(`ALTER TABLE "tournament_pairings" DROP CONSTRAINT "FK_4f70c0d8fa9e9ea442fa7a8756e"`);
        await queryRunner.query(`ALTER TABLE "tournament_pairings" DROP CONSTRAINT "FK_04e2b3dc93651026e3656f9c836"`);
        await queryRunner.query(`ALTER TABLE "tournament_pairings" DROP CONSTRAINT "FK_935d21edc31e8136616958c18a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_156afe22bb6ce336df01988d1e"`);
        await queryRunner.query(`DROP TABLE "tournament_pairings"`);
    }

}
