import { MigrationInterface, QueryRunner } from "typeorm";

// WHAT THIS FILE IS
// A migration generated by `npm run migration:generate` from the entities in
// src/modules/tournaments/entities. It adds the two tables of the tournaments
// feature:
//  - tournaments         one row per tournament: name, size (4 or 8 places),
//                        the board of its matches, status, creator, timestamps
//  - tournament_players  who registered; primary key (tournament_id, user_id)
//                        so nobody can register twice
// It runs after CreateMatches because both tables point to `users`.
//
// The CHECK constraints are a last line of defence: even a bug in the code
// cannot store a size other than 4 or 8, or a board the engine would refuse.
// Cancelling a tournament DELETES its row, and the registrations go with it
// (ON DELETE CASCADE).
//
// The long number in the file and class name is the creation time in
// milliseconds. TypeORM runs migrations in that order and records each name
// in the `migrations` table once it has run. DO NOT rename this file or class
// after it has run, and never change its SQL afterwards: change the entities
// and generate a NEW migration instead.
export class CreateTournaments1791481748307 implements MigrationInterface {
    name = 'CreateTournaments1791481748307'

    // up(): types first, then tables and indexes, and the foreign keys LAST
    // because they need every table to exist.
    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."tournaments_status_enum" AS ENUM('registering', 'running', 'finished')`);
        await queryRunner.query(`CREATE TABLE "tournaments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "status" "public"."tournaments_status_enum" NOT NULL DEFAULT 'registering', "size" smallint NOT NULL, "cols" smallint NOT NULL, "rows" smallint NOT NULL, "win_length" smallint NOT NULL, "theme" text NOT NULL DEFAULT 'classic', "created_by_id" uuid NOT NULL, "winner_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "started_at" TIMESTAMP WITH TIME ZONE, "ended_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "CHK_c4a1ce2648835df3ac01d5292f" CHECK ("win_length" >= 3 AND "win_length" <= LEAST("cols", "rows")), CONSTRAINT "CHK_778765c7163efab20c24364934" CHECK ("rows" BETWEEN 3 AND 12), CONSTRAINT "CHK_28e699b22682e4d40df8ca0c04" CHECK ("cols" BETWEEN 3 AND 12), CONSTRAINT "CHK_d611f7d9a851d39ce375022450" CHECK ("size" IN (4, 8)), CONSTRAINT "PK_6d5d129da7a80cf99e8ad4833a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5bdbbbf95bc2bcb5caada90f0c" ON "tournaments"  ("status") `);
        await queryRunner.query(`CREATE TABLE "tournament_players" ("tournament_id" uuid NOT NULL, "user_id" uuid NOT NULL, "joined_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7fb1310d0224d7eb26fcca79e28" PRIMARY KEY ("tournament_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_78684b0ff6001ae89d6e727672" ON "tournament_players"  ("user_id") `);
        // Foreign keys. A user who created or joined a tournament cannot be
        // deleted (RESTRICT); a deleted winner just leaves the field empty
        // (SET NULL); cancelling a tournament removes its registrations (CASCADE).
        await queryRunner.query(`ALTER TABLE "tournaments" ADD CONSTRAINT "FK_5b02d9854518630cd0f7e2e2ce8" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournaments" ADD CONSTRAINT "FK_5d6755f82a2eb49b3c1f5622cfc" FOREIGN KEY ("winner_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_players" ADD CONSTRAINT "FK_76e731e4992a85050d3cb75b2f4" FOREIGN KEY ("tournament_id") REFERENCES "tournaments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_players" ADD CONSTRAINT "FK_78684b0ff6001ae89d6e7276726" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    // down(): undoes up() in reverse order (foreign keys, then tables and
    // indexes, then the enum type). Used by `npm run migration:revert`.
    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tournament_players" DROP CONSTRAINT "FK_78684b0ff6001ae89d6e7276726"`);
        await queryRunner.query(`ALTER TABLE "tournament_players" DROP CONSTRAINT "FK_76e731e4992a85050d3cb75b2f4"`);
        await queryRunner.query(`ALTER TABLE "tournaments" DROP CONSTRAINT "FK_5d6755f82a2eb49b3c1f5622cfc"`);
        await queryRunner.query(`ALTER TABLE "tournaments" DROP CONSTRAINT "FK_5b02d9854518630cd0f7e2e2ce8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78684b0ff6001ae89d6e727672"`);
        await queryRunner.query(`DROP TABLE "tournament_players"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5bdbbbf95bc2bcb5caada90f0c"`);
        await queryRunner.query(`DROP TABLE "tournaments"`);
        await queryRunner.query(`DROP TYPE "public"."tournaments_status_enum"`);
    }

}
