import { MigrationInterface, QueryRunner } from "typeorm";

// WHAT THIS FILE IS
// The switch from JWT login to database sessions. It creates the `sessions`
// table (one row per login: the hash of the cookie's random token, whether
// it is a pending-2FA session, and when it expires) and removes the
// `refresh_tokens` table that only the JWT design needed.
//
// The CREATE statements were generated by `npm run migration:generate` from
// the Session entity. The DROP of `refresh_tokens` was ADDED BY HAND: the
// generator only compares tables that still have an entity, and the
// RefreshToken entity no longer exists, so it never notices the old table.
// Existing refresh tokens are lost on purpose: everyone has to log in again.
//
// The number in the file/class name is the creation time; never rename this
// file or edit it once it has run (see CreateIdentityTables for details).
export class ReplaceRefreshTokensWithSessions1791328373308 implements MigrationInterface {
    name = 'ReplaceRefreshTokensWithSessions1791328373308'

    // up(): creates `sessions` (table, indexes, foreign key), then drops
    // `refresh_tokens` (its indexes and foreign key go with the table).
    public async up(queryRunner: QueryRunner): Promise<void> {
        // token_hash is the SHA-256 of the cookie token, never the token.
        // pending_two_factor marks "password OK, 2FA code still needed".
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" text NOT NULL, "pending_two_factor" boolean NOT NULL DEFAULT false, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_abaa9e068cdd390bc5210f79884" UNIQUE ("token_hash"), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_085d540d9f418cfbdc7bd55bb1" ON "sessions"  ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9cfe37d28c3b229a350e086d94" ON "sessions"  ("expires_at") `);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        // Added by hand (see the header comment).
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
    }

    // down(): undoes up() in reverse. Recreates `refresh_tokens` exactly as
    // CreateRefreshTokens made it (empty: the old tokens are gone for good),
    // then removes `sessions`.
    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" text NOT NULL, "family_id" uuid NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_a7838d2ba25be1342091b6695f1" UNIQUE ("token_hash"), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ddc983c5f7bcf132fd8732c3f" ON "refresh_tokens"  ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d5e27da0cd39bc3bb2811fc8ba" ON "refresh_tokens"  ("family_id") `);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9cfe37d28c3b229a350e086d94"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_085d540d9f418cfbdc7bd55bb1"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
    }

}
