import { MigrationInterface, QueryRunner } from "typeorm";

// WHAT THIS FILE IS
// A migration: a versioned set of instructions that changes the database
// schema. This one was GENERATED by `npm run migration:generate`: TypeORM
// compared our entities (src/modules/users/entities/*.entity.ts) with the
// real database, saw that the tables did not exist, and wrote the SQL below.
//
// WHY THE FILE NAME STARTS WITH A LONG NUMBER
// 1791225849966 is the creation time in milliseconds. TypeORM sorts
// migrations by it, so they always run in the order they were created, and
// two migrations can never share a name. The same number is repeated in the
// class name below: TypeORM requires it. DO NOT rename this file or class
// once it has run, TypeORM would treat it as a brand new migration.
//
// HOW IT RELATES TO TYPEORM
// - `npm run migration:run` loads every file in this folder (see `migrations`
//   in config/database.config.ts), skips the ones already recorded in the
//   `migrations` table of Postgres, and calls `up()` on the new ones, inside
//   a transaction.
// - After a successful `up()`, TypeORM inserts this migration's name in the
//   `migrations` table. That is how it knows it has already run.
// - `npm run migration:revert` calls `down()` of the last executed migration
//   and removes its row from that table.
// - Because `synchronize` is off, migrations are the ONLY way the schema
//   changes. To change a table later, edit the entity and generate a NEW
//   migration; never edit one that has already run.
export class CreateIdentityTables1791225849966 implements MigrationInterface {
    name = 'CreateIdentityTables1791225849966'

    // up(): applies the change. Creates users, oauth_accounts and two_factor,
    // then the index on oauth_accounts.user_id, then the foreign keys. The
    // foreign keys come last because they need both tables to exist first.
    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" text NOT NULL, "display_name" text NOT NULL, "password_hash" text, "avatar_url" text, "locale" text NOT NULL DEFAULT 'en', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_a72fa0bb46a03bedcd1745efb41" UNIQUE ("display_name"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "oauth_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "provider" text NOT NULL, "provider_account_id" text NOT NULL, CONSTRAINT "UQ_f1daab3d50d1ce730369c01c57f" UNIQUE ("provider", "provider_account_id"), CONSTRAINT "PK_710a81523f515b78f894e33bb10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_22a05e92f51a983475f9281d3b" ON "oauth_accounts"  ("user_id") `);
        await queryRunner.query(`CREATE TABLE "two_factor" ("user_id" uuid NOT NULL, "secret" text NOT NULL, "enabled" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_162c7f53b41b84102a8e06eff18" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`ALTER TABLE "oauth_accounts" ADD CONSTRAINT "FK_22a05e92f51a983475f9281d3b0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "two_factor" ADD CONSTRAINT "FK_162c7f53b41b84102a8e06eff18" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    // down(): undoes up(), in the reverse order (foreign keys first, then the
    // tables, with `users` last because the others point to it). Used by
    // `npm run migration:revert`.
    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "two_factor" DROP CONSTRAINT "FK_162c7f53b41b84102a8e06eff18"`);
        await queryRunner.query(`ALTER TABLE "oauth_accounts" DROP CONSTRAINT "FK_22a05e92f51a983475f9281d3b0"`);
        await queryRunner.query(`DROP TABLE "two_factor"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22a05e92f51a983475f9281d3b"`);
        await queryRunner.query(`DROP TABLE "oauth_accounts"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
