import { MigrationInterface, QueryRunner } from "typeorm";

// WHAT THIS FILE IS
// A migration generated by `npm run migration:generate` from
// src/modules/users/entities/two-factor-backup-code.entity.ts. It adds the table
// of 2FA backup codes: the one-time codes a user can type instead of an
// authenticator code. One row per code, holding only a KEYED HASH of it (never
// the code), and `used_at`, set the first time it works.
//  - UNIQUE (user_id, code_hash): a user cannot hold the same code twice
//  - deleting a user deletes their codes (ON DELETE CASCADE)
//  - user_id is indexed: every check and count looks codes up by user
//
// DO NOT rename this file or class after it has run, and never change its SQL
// afterwards: change the entity and generate a NEW migration instead.
export class CreateTwoFactorBackupCodes1791589539286 implements MigrationInterface {
    name = 'CreateTwoFactorBackupCodes1791589539286'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "two_factor_backup_codes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "code_hash" text NOT NULL, "used_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_bdfdac161e2ae673e0728f1e3f6" UNIQUE ("user_id", "code_hash"), CONSTRAINT "PK_09d12fab70006efaa94f54e6871" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_943d6a21afeb35294f08e2fb76" ON "two_factor_backup_codes"  ("user_id") `);
        await queryRunner.query(`ALTER TABLE "two_factor_backup_codes" ADD CONSTRAINT "FK_943d6a21afeb35294f08e2fb763" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "two_factor_backup_codes" DROP CONSTRAINT "FK_943d6a21afeb35294f08e2fb763"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_943d6a21afeb35294f08e2fb76"`);
        await queryRunner.query(`DROP TABLE "two_factor_backup_codes"`);
    }

}
