import { MigrationInterface, QueryRunner } from "typeorm";

// WHAT THIS FILE IS
// A migration generated by `npm run migration:generate` from the entity
// src/modules/auth/entities/session.entity.ts. It adds the `sessions` table:
// one row per login. After a login the browser holds a random token in an
// httpOnly cookie, and this table stores only the SHA-256 hash of that token,
// so a leaked database cannot be used to hijack a login. Logout deletes the
// row, which ends the login immediately.
// It runs after CreateIdentityTables (the `users` table must exist, because
// sessions point to it) and AddTwoFactorLastUsedStep.
//
// The long number in the file and class name is the creation time in
// milliseconds. TypeORM runs migrations in that order and records each name
// in the `migrations` table once it has run. DO NOT rename this file or class
// after it has run, and never change its SQL afterwards: change the entity and
// generate a NEW migration instead.
export class CreateSessions1791329078678 implements MigrationInterface {
    name = 'CreateSessions1791329078678'

    // up(): applies the change. Order matters: the table first, then the
    // indexes, then the foreign key that points to `users`.
    public async up(queryRunner: QueryRunner): Promise<void> {
        // The table. `token_hash` is the SHA-256 of the cookie token (never
        // the token itself) and must be unique. `pending_two_factor` is true
        // while the password was right but the 2FA code has not been given yet
        // (such a session lasts 5 minutes and opens no normal route).
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" text NOT NULL, "pending_two_factor" boolean NOT NULL DEFAULT false, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_abaa9e068cdd390bc5210f79884" UNIQUE ("token_hash"), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        // Index on user_id: fast lookup of a user's sessions.
        await queryRunner.query(`CREATE INDEX "IDX_085d540d9f418cfbdc7bd55bb1" ON "sessions"  ("user_id") `);
        // Index on expires_at: fast deletion of expired sessions.
        await queryRunner.query(`CREATE INDEX "IDX_9cfe37d28c3b229a350e086d94" ON "sessions"  ("expires_at") `);
        // Foreign key to users. ON DELETE CASCADE: deleting a user deletes
        // all their sessions too.
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    // down(): undoes up() in reverse order (foreign key, indexes, then the
    // table). Used by `npm run migration:revert`.
    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9cfe37d28c3b229a350e086d94"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_085d540d9f418cfbdc7bd55bb1"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
    }

}
