import { MigrationInterface, QueryRunner } from "typeorm";

// WHAT THIS FILE IS
// A migration generated by `npm run migration:generate` from the entities in
// src/modules/matches/entities. It adds the three tables of the game:
//  - matches        one row per game: settings, status, timestamps
//  - match_players  who sits in which seat, and the result for each player
//  - match_moves    every move in order; the board is rebuilt from these
// It runs after CreateSessions and the earlier migrations because
// match_players and matches point to `users`.
//
// Postgres ENUM types (match status, end reason, player result) are created
// first because the tables use them, and are dropped last in down().
// The CHECK constraints are a last line of defence: even a bug in the code
// cannot store a seat other than 1 or 2, or a board the engine would refuse.
//
// The long number in the file and class name is the creation time in
// milliseconds. TypeORM runs migrations in that order and records each name
// in the `migrations` table once it has run. DO NOT rename this file or class
// after it has run, and never change its SQL afterwards: change the entities
// and generate a NEW migration instead.
export class CreateMatches1791336280175 implements MigrationInterface {
    name = 'CreateMatches1791336280175'

    // up(): applies the change. Order matters: types, then tables, then
    // indexes, and the foreign keys LAST because they need every table to
    // exist first.
    public async up(queryRunner: QueryRunner): Promise<void> {
        // match_players: composite primary key (match_id, seat) = a seat can
        // only be taken once; unique (match_id, user_id) = nobody plays
        // against themselves in the same match.
        await queryRunner.query(`CREATE TYPE "public"."match_players_result_enum" AS ENUM('win', 'loss', 'draw')`);
        await queryRunner.query(`CREATE TABLE "match_players" ("match_id" uuid NOT NULL, "seat" smallint NOT NULL, "user_id" uuid NOT NULL, "result" "public"."match_players_result_enum", CONSTRAINT "UQ_1795dc806841abffb7fab9bbb6a" UNIQUE ("match_id", "user_id"), CONSTRAINT "CHK_d04bf1cc22f452b4255ab56a71" CHECK ("seat" IN (1, 2)), CONSTRAINT "PK_27bfb3c0b7f4d05dd2093d88600" PRIMARY KEY ("match_id", "seat"))`);
        // Index on user_id: "my matches" (history) looks matches up by user.
        await queryRunner.query(`CREATE INDEX "IDX_979364322dfcb3b4710572b3f8" ON "match_players"  ("user_id") `);
        // matches: the game itself. The board is NOT here: it is rebuilt from
        // match_moves with the engine. The CHECKs mirror the engine's limits.
        await queryRunner.query(`CREATE TYPE "public"."matches_status_enum" AS ENUM('waiting', 'in_progress', 'finished', 'abandoned')`);
        await queryRunner.query(`CREATE TYPE "public"."matches_end_reason_enum" AS ENUM('win', 'draw', 'resign', 'disconnect')`);
        await queryRunner.query(`CREATE TABLE "matches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."matches_status_enum" NOT NULL DEFAULT 'waiting', "end_reason" "public"."matches_end_reason_enum", "cols" smallint NOT NULL, "rows" smallint NOT NULL, "win_length" smallint NOT NULL, "theme" text NOT NULL DEFAULT 'classic', "invited_user_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "started_at" TIMESTAMP WITH TIME ZONE, "ended_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "CHK_647626a1d916ebcf09326f7bd7" CHECK ("win_length" >= 3 AND "win_length" <= LEAST("cols", "rows")), CONSTRAINT "CHK_059e83f8acbd8c16be56613f28" CHECK ("rows" BETWEEN 3 AND 12), CONSTRAINT "CHK_dbc5c386dc8b3ef68386dd53c3" CHECK ("cols" BETWEEN 3 AND 12), CONSTRAINT "PK_8a22c7b2e0828988d51256117f4" PRIMARY KEY ("id"))`);
        // Index on status: lobbies and "active matches" filter on it.
        await queryRunner.query(`CREATE INDEX "IDX_a182c2c9602fbab4e0cf680090" ON "matches"  ("status") `);
        // match_moves: primary key (match_id, ply) = a move number can only
        // exist once, so two simultaneous requests cannot both store move 5.
        await queryRunner.query(`CREATE TABLE "match_moves" ("match_id" uuid NOT NULL, "ply" smallint NOT NULL, "seat" smallint NOT NULL, "col" smallint NOT NULL, "played_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_ad300d312e9a5a5b5be1b60cb6" CHECK ("col" >= 0), CONSTRAINT "CHK_49fbc4249d282a12791974c36d" CHECK ("seat" IN (1, 2)), CONSTRAINT "CHK_c0f1987369cce48154d34a5c2c" CHECK ("ply" >= 1), CONSTRAINT "PK_37fe0057fcac1f34de1301a6ce9" PRIMARY KEY ("match_id", "ply"))`);
        // Foreign keys. Deleting a match deletes its players and moves
        // (CASCADE). A user who has played CANNOT be deleted (RESTRICT) so a
        // match is never left half empty; how to handle account deletion is a
        // later decision. A deleted invited user just makes the match open
        // (SET NULL).
        await queryRunner.query(`ALTER TABLE "match_players" ADD CONSTRAINT "FK_065584e9a7b86a9ad63180af39e" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_players" ADD CONSTRAINT "FK_979364322dfcb3b4710572b3f84" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_712e1330920bcd76960b4863afe" FOREIGN KEY ("invited_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_moves" ADD CONSTRAINT "FK_d007c003e2099764904fd8312d5" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    // down(): undoes up() in reverse order (foreign keys, then tables and
    // indexes, then the enum types). Used by `npm run migration:revert`.
    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "match_moves" DROP CONSTRAINT "FK_d007c003e2099764904fd8312d5"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_712e1330920bcd76960b4863afe"`);
        await queryRunner.query(`ALTER TABLE "match_players" DROP CONSTRAINT "FK_979364322dfcb3b4710572b3f84"`);
        await queryRunner.query(`ALTER TABLE "match_players" DROP CONSTRAINT "FK_065584e9a7b86a9ad63180af39e"`);
        await queryRunner.query(`DROP TABLE "match_moves"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a182c2c9602fbab4e0cf680090"`);
        await queryRunner.query(`DROP TABLE "matches"`);
        await queryRunner.query(`DROP TYPE "public"."matches_end_reason_enum"`);
        await queryRunner.query(`DROP TYPE "public"."matches_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_979364322dfcb3b4710572b3f8"`);
        await queryRunner.query(`DROP TABLE "match_players"`);
        await queryRunner.query(`DROP TYPE "public"."match_players_result_enum"`);
    }

}
