import { MigrationInterface, QueryRunner } from "typeorm";

// WHAT THIS FILE IS
// A migration generated by `npm run migration:generate` from the entities in
// src/modules/friends/entities. It adds two tables:
//  - friendships  a friend request or an accepted friendship. ONE row per pair
//                 of players: the two ids are stored in order (low < high), so
//                 "A asks B" and "B asks A" can never be two rows. The CHECKs
//                 enforce that order and that the requester is one of the two.
//  - blocks       "blocker does not want to hear from blocked"; the pair is the
//                 primary key, and nobody can block themselves (CHECK).
// Deleting a user deletes their friendships and blocks (ON DELETE CASCADE).
//
// DO NOT rename this file or class after it has run, and never change its SQL
// afterwards: change the entities and generate a NEW migration instead.
export class CreateFriendsAndBlocks1791582418019 implements MigrationInterface {
    name = 'CreateFriendsAndBlocks1791582418019'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."friendships_status_enum" AS ENUM('pending', 'accepted')`);
        await queryRunner.query(`CREATE TABLE "friendships" ("user_low_id" uuid NOT NULL, "user_high_id" uuid NOT NULL, "requester_id" uuid NOT NULL, "status" "public"."friendships_status_enum" NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "accepted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "CHK_851264ceeb43f525b672ca048d" CHECK ("requester_id" IN ("user_low_id", "user_high_id")), CONSTRAINT "CHK_bb000cb01f591df14d7ef36d34" CHECK ("user_low_id" < "user_high_id"), CONSTRAINT "PK_8ec6d0e2adc0fb61ad328fa158b" PRIMARY KEY ("user_low_id", "user_high_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8d74a919d5522cc283fe7e5a89" ON "friendships"  ("user_high_id") `);
        await queryRunner.query(`CREATE TABLE "blocks" ("blocker_id" uuid NOT NULL, "blocked_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_2b7cba541b87a0384b09cf8db1" CHECK ("blocker_id" <> "blocked_id"), CONSTRAINT "PK_806f6a5d38d031cdd868fd5e37e" PRIMARY KEY ("blocker_id", "blocked_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8aa6c887bed61ad10829450f2f" ON "blocks"  ("blocked_id") `);
        await queryRunner.query(`ALTER TABLE "friendships" ADD CONSTRAINT "FK_bd96af74c9e984cc718ac0739f4" FOREIGN KEY ("user_low_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friendships" ADD CONSTRAINT "FK_8d74a919d5522cc283fe7e5a895" FOREIGN KEY ("user_high_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blocks" ADD CONSTRAINT "FK_74f530c6fbffc357047b263818d" FOREIGN KEY ("blocker_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blocks" ADD CONSTRAINT "FK_8aa6c887bed61ad10829450f2f0" FOREIGN KEY ("blocked_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "blocks" DROP CONSTRAINT "FK_8aa6c887bed61ad10829450f2f0"`);
        await queryRunner.query(`ALTER TABLE "blocks" DROP CONSTRAINT "FK_74f530c6fbffc357047b263818d"`);
        await queryRunner.query(`ALTER TABLE "friendships" DROP CONSTRAINT "FK_8d74a919d5522cc283fe7e5a895"`);
        await queryRunner.query(`ALTER TABLE "friendships" DROP CONSTRAINT "FK_bd96af74c9e984cc718ac0739f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8aa6c887bed61ad10829450f2f"`);
        await queryRunner.query(`DROP TABLE "blocks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d74a919d5522cc283fe7e5a89"`);
        await queryRunner.query(`DROP TABLE "friendships"`);
        await queryRunner.query(`DROP TYPE "public"."friendships_status_enum"`);
    }

}
