import { MigrationInterface, QueryRunner } from "typeorm";

// WHAT THIS FILE IS
// A migration generated by `npm run migration:generate` after adding
// `lastSeenAt` to the User entity. It adds ONE nullable column to `users`:
// the last time the user did something while logged in. "Online" is derived
// from it (seen in the last minute), until WebSockets give a better signal.
// Existing users get NULL, which just means "not seen yet".
//
// DO NOT rename this file or class after it has run, and never change its SQL
// afterwards: change the entity and generate a NEW migration instead.
export class AddUserLastSeen1791578255714 implements MigrationInterface {
    name = 'AddUserLastSeen1791578255714'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" ADD "last_seen_at" TIMESTAMP WITH TIME ZONE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_seen_at"`);
    }

}
