import { MigrationInterface, QueryRunner } from "typeorm";

// WHAT THIS FILE IS
// A migration generated by `npm run migration:generate` after adding `isBot` to
// the User entity. It adds ONE column to `users`: true for the computer
// opponents (AI_Easy, AI_Medium, AI_Hard), false for everybody else, including
// every existing user. A bot has no password, so nobody can log in as it.
//
// DO NOT rename this file or class after it has run, and never change its SQL
// afterwards: change the entity and generate a NEW migration instead.
export class AddUserIsBot1791589204014 implements MigrationInterface {
    name = 'AddUserIsBot1791589204014'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" ADD "is_bot" boolean NOT NULL DEFAULT false`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "is_bot"`);
    }

}
