import { MigrationInterface, QueryRunner } from "typeorm";

// WHAT THIS FILE IS
// A migration generated by `npm run migration:generate` from the entity
// src/modules/auth/entities/refresh-token.entity.ts. It adds the
// `refresh_tokens` table used by JWT login: one row per issued refresh token,
// so the server can revoke them (logout, stolen-token detection).
// The users/oauth/two_factor tables came from the previous migration
// (CreateIdentityTables); this one only adds the new table.
//
// The long number in the file and class name is the creation time in
// milliseconds. TypeORM runs migrations in that order and records each name
// in the `migrations` table once it has run. DO NOT rename this file or class
// after it has run, and never edit it afterwards: change the entity and
// generate a NEW migration instead.
export class CreateRefreshTokens1791287626176 implements MigrationInterface {
    name = 'CreateRefreshTokens1791287626176'

    // up(): applies the change. Order matters: the table first, then the
    // indexes, then the foreign key that points to `users`.
    public async up(queryRunner: QueryRunner): Promise<void> {
        // The table. `token_hash` is the SHA-256 of the refresh token (never
        // the token itself) and must be unique. `family_id` groups the tokens
        // that come from rotating one login. `revoked_at` is NULL while the
        // token is still usable.
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" text NOT NULL, "family_id" uuid NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_a7838d2ba25be1342091b6695f1" UNIQUE ("token_hash"), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        // Index on user_id: fast lookup of a user's tokens.
        await queryRunner.query(`CREATE INDEX "IDX_3ddc983c5f7bcf132fd8732c3f" ON "refresh_tokens"  ("user_id") `);
        // Index on family_id: fast "revoke the whole family" when an old
        // token is reused.
        await queryRunner.query(`CREATE INDEX "IDX_d5e27da0cd39bc3bb2811fc8ba" ON "refresh_tokens"  ("family_id") `);
        // Foreign key to users. ON DELETE CASCADE: deleting a user deletes
        // all their refresh tokens too.
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    // down(): undoes up() in reverse order (foreign key, indexes, then the
    // table). Used by `npm run migration:revert`.
    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5e27da0cd39bc3bb2811fc8ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ddc983c5f7bcf132fd8732c3f"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
    }

}
